keycloak.client-id=${KEYCLOAK_CLIENT_ID}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}
keycloak.url=${KEYCLOAK_URL}

mp.jwt.verify.publickey.location=${KEYCLOAK_PUBLIC_KEY}
mp.jwt.verify.issuer=${KEYCLOAK_ISSUER}

quarkus.log.category."io.smallrye.jwt".level=DEBUG
quarkus.log.category."com.denisenko.service.AccessControlService".level=DEBUG
quarkus.config.locations=access-rules.yml