replicaCount: 1

image:
  repository: apicurio/apicurio-registry-mem
  pullPolicy: IfNotPresent
  tag: "2.6.2.Final"

service:
  type: ClusterIP
  port: 8080

env:
  JAVA_OPTIONS: -Dquarkus.http.host=0.0.0.0

nameOverride: "schema-registry"
fullnameOverride: "schema-registry"