quarkus.http.port= ${SERVER_PORT}
quarkus.log.category."com.denisenko.service.PrintService".level=DEBUG

printers.printers-list[0].name=KitchenPrinter
printers.printers-list[0].ip-address=192.168.1.0
printers.printers-list[0].port=9100
printers.printers-list[0].location=kitchen
printers.printers-list[0].emulator-url=${PRINT_EMULATOR_URL}
printers.printers-list[0].is-fiscal=false

printers.printers-list[1].name=BarPrinter
printers.printers-list[1].ip-address=192.168.1.11
printers.printers-list[1].port=9100
printers.printers-list[1].location=bar
printers.printers-list[1].emulator-url=${PRINT_EMULATOR_URL}
printers.printers-list[1].is-fiscal=false

printers.printers-list[2].name=CashDeskPrinter
printers.printers-list[2].ip-address=192.168.1.12
printers.printers-list[2].port=9100
printers.printers-list[2].location=cash-desk
printers.printers-list[2].emulator-url=${PRINT_EMULATOR_URL}
printers.printers-list[2].is-fiscal=true