quarkus.http.port=${SERVER_PORT}
quarkus.redis.hosts=redis://${REDIS_HOST}:${REDIS_PORT}
quarkus.redis.client-type=standalone

print-service.url=${PRINT_SERVICE_URL}
print-service.fiscal-shift-path=${PRINT_FISCAL_SHIFT_PATH}
print-service.fiscal-order-path=${PRINT_FISCAL_ORDER_PATH}
print-service.retry-attempts=${PRINT_RETRY_ATTEMPTS}
print-service.retry-delay=${PRINT_RETRY_DELAY}

ofd-service.url=${OFD_SERVICE_URL}
ofd-service.open-shift-path=${OFD_OPEN_SHIFT_PATH}
ofd-service.close-shift-path=${OFD_CLOSE_SHIFT_PATH}
ofd-service.close-order-path=${OFD_CLOSE_ORDER_PATH}
ofd-service.retry-attempts=${OFD_RETRY_ATTEMPTS}
ofd-service.retry-delay=${OFD_RETRY_DELAY}

mp.messaging.connector.smallrye-kafka.apicurio.registry.url=${SCHEMA_REGISTRY_URL}

mp.messaging.outgoing.shift-opened.connector=smallrye-kafka
mp.messaging.outgoing.shift-opened.topic=${KAFKA_TOPIC_SHIFT_OPENED}
mp.messaging.outgoing.shift-opened.bootstrap.servers=${BOOTSTRAP_SERVERS}
mp.messaging.outgoing.shift-opened.value.serializer=io.apicurio.registry.serde.avro.AvroKafkaSerializer
mp.messaging.outgoing.shift-opened.apicurio.registry.auto-register=true
mp.messaging.outgoing.shift-opened.apicurio.registry.use-schema-id=false
mp.messaging.outgoing.shift-opened.apicurio.registry.find-latest=false

mp.messaging.outgoing.shift-closed.connector=smallrye-kafka
mp.messaging.outgoing.shift-closed.topic=${KAFKA_TOPIC_SHIFT_CLOSED}
mp.messaging.outgoing.shift-closed.bootstrap.servers=${BOOTSTRAP_SERVERS}
mp.messaging.outgoing.shift-closed.value.serializer=io.apicurio.registry.serde.avro.AvroKafkaSerializer
mp.messaging.outgoing.shift-closed.apicurio.registry.auto-register=true
mp.messaging.outgoing.shift-closed.apicurio.registry.use-schema-id=false
mp.messaging.outgoing.shift-closed.apicurio.registry.find-latest=false

apicurio.registry.url=${SCHEMA_REGISTRY_URL}
apicurio.registry.auto-register=true

#reports.reports[0].name=
#reports.reports[0].description=
#reports.reports[0].field=
#reports.reports[0].operation=

#reports.reports[1].name=
#reports.reports[1].description=
#reports.reports[1].field=
#reports.reports[1].operation=